server:
  port: 9001
spring:
  application:
    name: base-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.243.33:8848,192.168.243.34:8848
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

