server:
  port: 8680
spring:
  application:
    name: base-gateway
  zipkin:
    base-url: http://192.168.243.33:9411/ # zipkin的地址
    discovery-client-enabled: false  #让注册中心把它当成url  而不要当成服务
  sleuth:
    sampler:
      probability: 1.0 #标识全部采集{0-1}
  cloud:
    nacos:
      discovery:
        server-addr: 192.168.243.33:8848,192.168.243.34:8848
    gateway:
      discovery:
        locator:
          enabled: true  #开启从注册中心动态创建路由的功能
          lower-case-service-id: true #使用小写服务名，默认是大写

