server:
  port: 9005
spring:
  profiles:
    active: dev
  application:
    name: base-admin
  cloud:
    nacos:
      server-addr: 192.168.243.33:8848,192.168.243.34:8848
mybatis-plus:
  mapper-locations: classpath:/mapper/*Mapper.xml
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
user:
  name: yuyanjia
  id: 889900
  code: ddd111222
