server:
  port: 8681
spring:
  profiles:
    active: test
  application:
    name: base-admin
  cloud:
    nacos:
      server-addr: 192.168.243.33:8848,192.168.243.34:8848
  zipkin:
    base-url: http://192.168.243.33:9411
    sleuth:
      sampler:
        probability: 0.5 #设置Sleuth的抽样收集概率
  #数据库配置
  datasource:
    url: jdbc:mysql://192.168.243.20:9097/sa_project?useUnicode=true&useSSL=false&characterEncoding=utf-8
    username: root
    password: 'b#12345678'
    # 使用druid数据源
    type: com.alibaba.druid.pool.DruidDataSource
    driver-class-name: com.mysql.cj.jdbc.Driver
mybatis:
  mapper-locations:
    - classpath:dao/*.xml
    - classpath*:com/**/mapper/*.xml
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  file:
    path: admin-client.log #添加开启admin的日志监控
user:
  name: yuyanjia
  id: 889900
  code: ddd111222
