server:
  port: 8683
spring:
  application:
    name: base-protal
  cloud:
    nacos:
      server-addr: 192.168.243.33:8848,192.168.243.34:8848
  zipkin:
    base-url: http://192.168.243.33:9411
  sleuth:
    sampler:
      probability: 0.5 #设置Sleuth的抽样收集概率